"""
Test new DOCX features: lists, page headers/footers, page numbers
"""

import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from report_genius.templates import (
    PortableViewTemplate,
    Section,
    SectionType,
    HeaderConfig,
    ListConfig,
    PageHeaderFooterConfig,
    LayoutConfig,
    Alignment,
    TextConfig,
    HyperlinkDef,
)
from report_genius.rendering import DocxRenderer as SOTADocxRenderer


def test_bullet_list():
    """Test bullet list rendering."""
    template = PortableViewTemplate(
        name="List Test",
        entity_def="TestEntity",
        sections=[
            Section(
                type=SectionType.HEADER,
                header_config=HeaderConfig(
                    static_title="List Feature Test",
                    title_font="Arial",
                    title_size=20,
                    title_color="#333333",
                ),
            ),
            Section(
                type=SectionType.LIST,
                title="Requirements",
                list_config=ListConfig(
                    list_type="bullet",
                    items=[
                        "First requirement",
                        "Second requirement with {FieldA}",
                        "Third requirement",
                    ],
                ),
            ),
            Section(
                type=SectionType.LIST,
                title="Steps",
                list_config=ListConfig(
                    list_type="number",
                    items=[
                        "Step one",
                        "Step two",
                        "Step three",
                    ],
                ),
            ),
        ],
    )
    
    renderer = SOTADocxRenderer(template)
    doc_bytes = renderer.render_to_bytes()
    
    output_path = Path(__file__).parent.parent / "reports" / "test_lists.docx"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_bytes(doc_bytes)
    print(f"✅ List test saved to: {output_path}")


def test_page_header_footer():
    """Test page header and footer with page numbers."""
    template = PortableViewTemplate(
        name="Header Footer Test",
        entity_def="TestEntity",
        layout=LayoutConfig(
            page_header=PageHeaderFooterConfig(
                left_text="Company Name",
                center_text="CONFIDENTIAL",
                right_text="Report ID: 12345",
                font_size=9,
            ),
            page_footer=PageHeaderFooterConfig(
                left_text="Generated by Report Genius",
                include_page_number=True,
                page_number_format="Page {page} of {total}",
                right_text="[Date(Format='d')]",
                font_size=8,
            ),
        ),
        sections=[
            Section(
                type=SectionType.HEADER,
                header_config=HeaderConfig(
                    static_title="Document with Header/Footer",
                    title_font="Calibri",
                    title_size=24,
                    title_color="#1a365d",
                    title_alignment=Alignment.CENTER,
                ),
            ),
            Section(
                type=SectionType.TEXT,
                title="Introduction",
                text_config={"content": "This document demonstrates page headers and footers with automatic page numbering."},
            ),
            Section(
                type=SectionType.TEXT,
                title="More Content",
                text_config={"content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " * 20},
            ),
        ],
    )
    
    renderer = SOTADocxRenderer(template)
    doc_bytes = renderer.render_to_bytes()
    
    output_path = Path(__file__).parent.parent / "reports" / "test_header_footer.docx"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_bytes(doc_bytes)
    print(f"✅ Header/footer test saved to: {output_path}")


def test_combined_features():
    """Test all new features together."""
    template = PortableViewTemplate(
        name="Combined Features Test",
        entity_def="RFI",
        layout=LayoutConfig(
            orientation="portrait",
            page_header=PageHeaderFooterConfig(
                left_text="Kahua Inc.",
                center_text="Request for Information",
                include_page_number=False,
                font_size=10,
            ),
            page_footer=PageHeaderFooterConfig(
                center_text=None,
                include_page_number=True,
                page_number_format="Page {page} of {total}",
                font_size=9,
            ),
        ),
        sections=[
            Section(
                type=SectionType.HEADER,
                header_config=HeaderConfig(
                    static_title="Beau's RFI Template",
                    title_font="Comic Sans MS",
                    title_size=28,
                    title_color="#0000FF",
                    title_bold=True,
                    title_alignment=Alignment.CENTER,
                    subtitle_template="RFI #{Number} - {Subject}",
                ),
            ),
            Section(
                type=SectionType.LIST,
                title="Action Items",
                list_config=ListConfig(
                    list_type="bullet",
                    items=[
                        "Review attached documents",
                        "Provide technical clarification",
                        "Submit response by {DueDate}",
                    ],
                ),
            ),
            Section(
                type=SectionType.LIST,
                title="Review Process",
                list_config=ListConfig(
                    list_type="number",
                    items=[
                        "Initial review by project manager",
                        "Technical review by engineering",
                        "Final approval by client",
                        "Response submitted to contractor",
                    ],
                ),
            ),
        ],
    )
    
    renderer = SOTADocxRenderer(template)
    doc_bytes = renderer.render_to_bytes()
    
    output_path = Path(__file__).parent.parent / "reports" / "test_combined_features.docx"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_bytes(doc_bytes)
    print(f"✅ Combined features test saved to: {output_path}")


def test_hyperlinks():
    """Test hyperlink rendering."""
    template = PortableViewTemplate(
        name="Hyperlink Test",
        entity_def="TestEntity",
        sections=[
            Section(
                type=SectionType.HEADER,
                header_config=HeaderConfig(
                    static_title="Hyperlink Feature Test",
                    title_font="Arial",
                    title_size=20,
                    title_color="#333333",
                ),
            ),
            Section(
                type=SectionType.TEXT,
                title="Related Links",
                text_config=TextConfig(
                    content="For more information, see the links below:",
                    hyperlinks=[
                        HyperlinkDef(
                            text="Visit Kahua Website",
                            url="https://www.kahua.com",
                            tooltip="Open Kahua homepage"
                        ),
                        HyperlinkDef(
                            text="View Documentation",
                            url="https://docs.kahua.com",
                        ),
                        HyperlinkDef(
                            text="Open in Kahua",
                            url="{WebUrl}",  # Dynamic URL from entity
                            tooltip="Open this record in Kahua"
                        ),
                    ],
                ),
            ),
        ],
    )
    
    renderer = SOTADocxRenderer(template)
    doc_bytes = renderer.render_to_bytes()
    
    output_path = Path(__file__).parent.parent / "reports" / "test_hyperlinks.docx"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_bytes(doc_bytes)
    print(f"✅ Hyperlink test saved to: {output_path}")


if __name__ == "__main__":
    print("Testing new DOCX features...\n")
    
    test_bullet_list()
    test_page_header_footer()
    test_combined_features()
    test_hyperlinks()
    
    print("\n✅ All tests completed! Check the reports/ folder for output files.")
